name: noori_basirat_smart_school
description: Noori Basirat Smart School - Islamic Education with 12 Languages & Halal Ads
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.2.0
flutter:
  uses-material-design: true
