name: noori_basirat_smart_school
description: Holy Quran App by FanzeTech
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^4.0.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
